### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by elijahzyx** [tim03we/ItemSign#1]
Tim, bei mir gibt es nach dem Upload des Plugin und nach einem Server restart der Befehl /itemsing und /isign nicht bitte hilf mir xD

**Comment by tim03we** [comment]
Die Befehle sind doch vorhanden? /itemsign oder /isign

**Comment by elijahzyx** [comment]
Wenn ich /ising oder /itemsing eingebe kommt nur: Unbekannter Befehl

**Comment by tim03we** [comment]
Also so wie du mir die Befehle schreibst, würden sie mir auch falsch angezeigt werden. Überprüfe bitte ob du sie auch richtig schreibst, den laut deiner Nachricht, scheint dies nicht so.

**Comment by elijahzyx** [comment]
Ich habe sie richtig geschrieben. Liegt es vllt daran, dass das Plugin ItemSign**-master**.phar heißt? Die Plugins gehen bei mir irgendwie nie.

**Comment by tim03we** [comment]
Selbst konvertiert?

**Comment by elijahzyx** [comment]
Nö, mit deiner Webseite. (http://paltrygamer.bplaced.net/converter/)

**Comment by tim03we** [comment]
Wird das Plugin überhaupt angezeigt?

**Comment by elijahzyx** [comment]
Nein.

**Comment by elijahzyx** [comment]
Und es stehen auch keine Fehlermeldungen in der Console.

**Comment by tim03we** [comment]
Dann wurde das Plugin falsch Konvertiert...
Nutze bitte diese PHAR Datei: http://poggit.pmmp.io/ci/tim03we/ItemSign

**Comment by tim03we** [comment]
Link ist gleich verfügbar.

**Comment by elijahzyx** [comment]
ok

**Comment by tim03we** [comment]
Jetzt. http://poggit.pmmp.io/ci/tim03we/ItemSign

**Comment by elijahzyx** [comment]
Jo jetzt geht es danke. Also lag es daran dass beim Converten die Poggit Datei gefehlt hat?

**Comment by tim03we** [comment]
Nein. Das ZIP Archive wurde wohl falsch Konvertiert und dadurch wurde wohl eine fehlerhafte PHAR Datei erstellt.

**Comment by elijahzyx** [comment]
Und kann man das fixen, weil ich hätte noch paar so ZIP Plugins von Github?

**Comment by tim03we** [comment]
Wenn man die Schritte der Seite befolgt, sollten keine Probleme auftreten.

**Comment by elijahzyx** [comment]
Welcher?

**Comment by elijahzyx** [comment]
Achso von deiner?

**Comment by tim03we** [comment]
Befolge die Schritte der Konverter Seite und es sollte einwandfrei klappen.
Es kann sein, dass die Schritte der Seite aber auch nicht mehr aktuell sind, dass weiß ich derzeit nicht.
Nutze stattdessen: http://teamfalldown.de/converter
